/**
 * Shared location display names per state for bulk scripts and state backfill.
 * Keys must match lib/location-states.ts (e.g. "Jammu & Kashmir", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar").
 */
export const LOCATIONS_BY_STATE: Record<string, string[]> = {
  "Jammu & Kashmir": [
    "Srinagar", "Jammu", "Anantnag", "Baramulla", "Sopore", "Pulwama", "Budgam", "Kupwara", "Rajouri", "Poonch",
    "Kathua", "Udhampur", "Ramban", "Kishtwar", "Doda", "Shopian", "Kulgam", "Bandipora", "Ganderbal", "Reasi",
    "Samba", "Leh", "Gulmarg", "Pahalgam", "Sonamarg", "Patnitop", "Vaishno Devi", "Nathatop", "Banihal", "Bhaderwah",
    "Chenani", "Ramnagar", "Akhnoor", "RS Pura", "Hiranagar", "Bishnah", "Marh", "Suchetgarh", "Vijaypur", "Samba City",
    "Nowshera", "Sunderbani", "Kalakote", "Mendhar", "Surankote", "Mandi", "Haveli", "Thanna Mandi", "Darhal", "Budhal",
    "Manjakote", "Behrote", "Kotranka", "Ukhral", "Gulabgarh", "Bhadarwah", "Padder", "Marwah", "Warwan", "Chatroo",
    "Zainapora", "Keller", "Hirpora", "Hermain", "Newa", "Bijbehara", "Verinag", "Dooru", "Kokernag", "Pahalgam East",
    "Mattan", "Qazigund", "Seer Hamdan", "Shangus", "Breng Valley", "Naidkhai", "Sumbal", "Bandipora Town", "Hajin", "Tulail",
    "Gurez", "Lolab", "Handwara", "Langate", "Sogam", "Karnah", "Tangdhar", "Uri", "Boniyar", "Wagoora",
    "Magam", "Chadoora", "Narbal", "Pampore", "Kakapora", "Tral", "Awantipora", "Lassipora", "Zainakote", "Nowpora",
    "Wanpoh", "Khrew", "Batamaloo", "Rajbagh", "Lal Chowk", "Dalgate", "Hazratbal", "Soura", "Bemina", "Panthachowk",
    "Zakura", "Khonmoh", "Pantha Chowk", "Sanat Nagar", "Rangreth", "Humhama", "Budgam Town", "Chadoora", "Magam", "Charar-i-Sharif",
    "Beerwah", "Kreeri", "Sopore Town", "Rafiabad", "Dangiwacha", "Tarzoo", "Wagoora", "Mawar", "Amargarh", "Pattan",
    "Tangmarg", "Kunzer", "Drangbal", "Gulmarg Gandola", "Affarwat", "Alpather", "Khilanmarg", "Drung", "Sheikhpora", "Watlab",
    "Baniyari", "Asham", "Gureze", "Dawar", "Tikkar", "Chandi Mandir", "Khour", "Hamirpur", "Satwari", "Janipur",
    "Bakshi Nagar", "Gandhi Nagar", "Trikuta Nagar", "Nagrota", "Kunjwani", "Channi Himmat", "Sidhra", "Sainik Colony", "Talab Tillo", "Bhagwati Nagar",
    "Bahu Fort Area", "Railhead Complex", "Shastri Nagar", "Sunjwan", "Old City Jammu", "Jewel Chowk", "Gumat", "Nai Basti Jammu", "Shakti Nagar", "Peer Mitha",
    "Rehari Colony", "Bhore Camp", "Lower Roop Nagar", "Upper Roop Nagar", "Gole Market", "Residency Road Jammu", "Canal Road Jammu", "Dogra Chowk", "Raghunath Bazar", "Gandhi Bazar Jammu",
    "Raghunath Temple Area", "Pacca Danga", "Nanak Nagar", "Chowadi", "Digiana", "Kachi Chawni", "Sarwal", "Ashok Nagar Jammu", "Choudhary Nagar", "Bathindi",
    "Mandal", "Phallain", "Majalta", "Jakh", "Simbal Camp", "Damana", "Muthi", "Gajansoo", "Bain Bajalta", "Mishriwala",
    "Pargwal", "Dhar Mantalai", "Koteranka", "Noori Chhamb", "Sudhmahadev", "Kud", "Batote", "Ramsu", "Ramsoo", "Chanderkote",
    "Panthyal", "Dool", "Dhar Bhatti", "Thathri", "Gandoh", "Assar", "Palmar", "Dhandal", "Bhadarwah Valley", "Chinta Valley",
    "Paddar Valley", "Warwan Valley", "Margan Top", "Sinthan Top", "Peer Ki Gali", "Banihal Pass", "Jawahar Tunnel", "Nashri", "Cafeteria Morh", "Sudhmahadev Temple",
    "Mansar Lake", "Surinsar Lake", "Bahu Fort", "Mubarak Mandi", "Amar Mahal Palace", "Peer Baba Dargah", "Shiv Khori", "Sheetla Mata", "Sanasar", "Patnitop Resort",
    "Natha Top", "Baba Dhansar", "Kailash Kund", "Machail", "Kishtwar NP", "Marwah Valley", "Leh Road Junction", "Zero Bridge Srinagar", "Boulevard Road", "Residency Road Srinagar",
    "Maisuma", "Nowhatta", "Bohri Kadal", "Zaldagar", "Safakadal", "Rainawari", "Khanyar", "Habba Kadal", "Nawakadal", "Badiyari",
    "Barbarshah", "Shivpora", "Wazir Bagh", "Gogji Bagh", "Jawahar Nagar Srinagar", "Harwan", "Dachigam", "Nishat", "Chashme Shahi", "Pari Mahal",
    "Shankaracharya Hill", "Hari Parbat", "Naidkhai", "Nagin Lake", "Dal Lake", "Wular Lake", "Manasbal Lake", "Anchar Lake", "Hokersar Wetland", "Tosamaidan",
    "Yusmarg", "Doodhpathri", "Aharbal Waterfall", "Konsarnag", "Kounsarnag", "Tarsar", "Marsar", "Gangabal", "Naranag", "Vishansar",
    "Krishansar", "Gadsar", "Satsar", "Sheshnag Lake", "Kolahoi Glacier", "Machoi Glacier", "Drass", "Kargil", "Zanskar", "Nubra",
    "Anantnag City", "Mattan Martand", "Bijbehara Town", "Islamabad", "Larkipora", "Sagam", "Sirhama", "Kukarnag", "Achabal", "Seer",
    "Dialgam", "Khull", "Khovripora", "Chitragam", "Panzgam", "Naidkhai", "Wathal Naka", "Sopore Fruit Mandi", "Delina", "Khadanyar",
  ],
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Kakinada",
    "Kadapa",
    "Anantapur",
    "Vizianagaram",
    "Eluru",
    "Ongole",
    "Chittoor",
    "Hindupur",
    "Srikakulam",
    "Adoni",
    "Tenali",
    "Proddatur",
    "Machilipatnam",
    "Bhimavaram",
    "Narasaraopet",
    "Gudivada",
    "Tadipatri",
    "Nandyal",
    "Chilakaluripet",
    "Markapur",
    "Kavali",
    "Madanapalle",
    "Guntakal",
    "Dharmavaram",
    "Tadepalligudem",
    "Bapatla",
    "Chirala",
    "Palasa",
    "Ponnur",
    "Gudur",
    "Jaganmohan Reddy Nagar",
    "Repalle",
    "Amalapuram",
    "Samarlakota",
    "Pithapuram",
    "Bobbili",
    "Parvathipuram",
    "Narsipatnam",
    "Payakaraopet",
    "Anakapalle",
    "Bheemunipatnam",
    "Gajuwaka",
    "Pendurthi",
    "Waltair",
    "Rushikonda",
    "Madhurawada",
    "MVP Colony",
    "Dwaraka Nagar Vizag",
    "Steel Plant Area Vizag",
    "Ukkunagaram",
    "Gostani",
    "Bheemunipatnam Beach",
    "Yarada",
    "Thotlakonda",
    "Simhachalam",
    "Kailasagiri",
    "Beach Road Vizag",
    "RK Beach",
    "Lawsons Bay",
    "Tenneti Park",
    "Bheemili",
    "Vizag Port",
    "Gangavaram Port",
    "Nakkapalli",
    "Munagapaka",
    "Atchutapuram",
    "Rambilli",
    "Parawada",
    "Pedagantyada",
    "Kommadi",
    "Madhurawada Town",
    "Kapuluppada",
    "Bheemunipatnam Fisheries",
    "Naidupeta",
    "Sullurpet",
    "Atmakur (Nellore)",
    "Kovur",
    "Bitragunta",
    "Venkatagiri",
    "Podalakur",
    "Udayagiri",
    "Martur",
    "Allur",
    "Vinukonda",
    "Sattenapalle",
    "Piduguralla",
    "Macherla",
    "Gurazala",
    "Karempudi",
    "Ipur",
    "Phirangipuram",
    "Edlapadu",
    "Tadikonda",
    "Thulluru",
    "Mangalagiri",
    "Undavalli",
    "Amaravati",
    "Undavalli Caves",
    "Kondaveedu",
    "Nagarjunasagar",
    "Mopidevi",
    "Repalle Town",
    "Nizampatnam",
    "Bapatla Beach",
    "Chirala Beach",
    "Vetapalem",
    "Inkollu",
    "Kandukur",
    "Singarayakonda",
    "Darsi",
    "Kanigiri",
    "Podili",
    "Giddalur",
    "Cumbum (AP)",
    "Koilkuntla",
    "Allagadda",
    "Srisailam",
    "Atmakur (Kurnool)",
    "Nandyal Town",
    "Dhone",
    "Panyam",
    "Gospadu",
    "Pamulapadu",
    "Mantralayam",
    "Adoni Town",
    "Yemmiganur",
    "Devanakonda",
    "Alur",
    "Kosigi",
    "Banaganapalle",
    "Nandikotkur",
    "Gadivemula",
    "Betamcherla",
    "Gorantla",
    "Garbham",
    "Puttaparthi",
    "Bukkapatnam",
    "Penukonda",
    "Kadiri",
    "Kalyanadurgam",
    "Rayadurg",
    "Uravakonda",
    "Guntakal Junction",
    "Tadpatri",
    "Singanamala",
    "Pamidi",
    "Kanekal",
    "Beluguppa",
    "Yadiki",
    "Raptadu",
    "Garladinne",
    "Settur",
    "Agali",
    "Hindupur Town",
    "Parigi",
    "Lepakshi",
    "Madakasira",
    "Brahmanapalle",
    "Mudigubba",
    "Gudibanda",
    "Talupula",
    "Somandepalli",
    "Amarapuram",
    "Rajampet",
    "Rayachoti",
    "Pulivendla",
    "Mydukur",
    "Jammalamadugu",
    "Kondapuram",
    "Badvel",
    "Khajipeta",
    "Vontimitta",
    "Sidhout",
    "Tirupati City",
    "Chandragiri",
    "Srikalahasti",
    "Sullurpet (Tirupati)",
    "Nagalapuram",
    "Renigunta",
    "Pakala",
    "Punganur",
    "Kuppam",
    "Palamaner",
    "Gangadhara Nellore",
    "Yerpedu",
    "Varadaiahpalem",
    "Nagari",
    "Puttur (AP)",
    "Tarichedu",
    "Vijayapuram",
    "Ramachandrapuram",
    "Pedana",
    "Bantumilli",
    "Nidadavolu",
    "Kovvur",
    "Palakol",
    "Jangareddygudem",
    "Polavaram",
    "Bhadrachalam (AP)",
    "Kunavaram",
    "Dummugudem",
    "Kothagudem (AP)",
    "Yellandu",
    "Jagityal (AP)",
    "Bodhan (AP)",
    "Siddipet (AP)",
    "Karimnagar (AP)",
    "Warangal (AP)",
    "Khammam (AP)",
    "Nizamabad (AP)",
    "Adilabad (AP)",
    "Mancherial (AP)",
    "Peddapalli (AP)",
    "Rajam",
    "Narasannapeta",
    "Palasa Town",
    "Tekkali",
    "Amadalavalasa",
    "Etcherla",
    "Gara",
    "Sompeta",
    "Mandasa",
    "Hiramandalam",
    "Vizianagaram City",
    "Salur",
    "Gajapatinagaram",
    "Cheepurupalli",
    "Srungavarapukota",
    "Komarada",
    "Kurupam",
    "Makkuva",
    "Ramabhadrapuram",
    "Nellimarla",
    "Kakinada City",
    "Peddapuram",
    "Tuni",
    "Prathipadu",
    "Yeleswaram",
    "Kirlampudi",
    "Jaggampeta",
    "Ramachandrapuram (EG)",
    "Ravulapalem",
    "Mandapeta",
    "Razole",
    "Mummidivaram",
    "Amalapuram Town",
    "Alamuru",
    "Ambajipeta",
    "Malikipuram",
    "Katrenikona",
    "Uppalaguptam",
    "Sakhinetipalli",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tezpur (Ar)",
    "Along",
    "Ziro",
    "Bomdila",
    "Tawang",
    "Roing",
    "Tezu",
    "Namsai",
    "Khonsa",
    "Changlang",
    "Deomali",
    "Miao",
    "Jairampur",
    "Daporijo",
    "Aalo",
    "Anini",
    "Mechuka",
    "Yingkiong",
    "Mariyang",
    "Jengging",
    "Tuting",
    "Tato",
    "Gelling",
    "Bame",
    "Menchukha",
    "Monigong",
    "Siyom",
    "Rumgong",
    "Pangin",
    "Nari",
    "Koyu",
    "Boleng",
    "Kaying",
    "Mebo",
    "Nampong",
    "Lazu",
    "Hayuliang",
    "Hawai",
    "Vijoynagar",
    "Longding",
    "Pongchau",
    "Wakka",
    "Pumao",
    "Niausa",
    "Bordumsa",
    "Manmao",
    "Namchik",
    "Seijosa",
    "Balipara (Ar)",
    "Bhalukpong",
    "Bomdila Town",
    "Dirang",
    "Sangti",
    "Thembang",
    "Kalaktang",
    "Shergaon",
    "Rupa",
    "Nafra",
    "Singchung",
    "Buragaon",
    "Seppa",
    "Pakke-Kessang",
    "Bameng",
    "Pipu",
    "Champi",
    "Chukham",
    "Tali",
    "Huri",
    "Tamen",
    "Dollungmukh",
    "Nyapin",
    "Nacho",
    "Damin",
    "Koloriang",
    "Taliha",
    "Sarli",
    "Khellong",
    "Pangin Town",
    "Padi",
    "Tirbin",
    "Jonai",
    "Dhemaji (Ar)",
    "Sille",
    "Bungke",
    "Kombo",
    "Sissi",
    "Payum",
    "Remoxing",
    "Riga",
    "Migging",
    "Miri",
    "Geba",
    "Jibo",
    "Nyikpak",
    "Nefra",
    "Manigong",
    "Mibang",
    "Koyu Village",
    "Panka",
    "Oju",
    "Liromoba",
    "Yagrung",
    "Singa",
    "Pame",
    "Ligu",
    "Joram",
    "Tato Village",
    "Goiliang",
    "Damro",
    "Nari Village",
    "Dambuk",
    "Hunli",
    "Etalin",
    "Kibithoo",
    "Walong",
    "Dong",
    "Dong Village",
    "Hayuliang Town",
    "Chaglagam",
    "Gandhigram (Ar)",
    "Miao Town",
    "Jairampur Town",
    "Borduria",
    "Namphake",
    "Margherita (Ar)",
    "Lohit River Area",
    "Parasuram Kund",
    "Namsai Town",
    "Golden Pagoda Area",
    "Chongkham",
    "Lathao",
    "Chapakhowa",
    "Mahadevpur",
    "Mahadevpur Town",
    "Rupai",
    "Namsai District HQ",
    "Tengapani",
    "Khonsa Town",
    "Longding Town",
    "Kanubari",
    "Pongchau Village",
    "Niausa Village",
    "Pumao Village",
    "Tissa",
    "Khimiyong",
    "Sengha",
    "Lazu Village",
    "Roing Town",
    "Bhismaknagar",
    "Nehru Van Udyan Area",
    "Mehao WLS Area",
    "Rabina",
    "Ita Fort Area",
    "Papum Pare",
    "Doimukh",
    "Yupia",
    "Banderdewa",
    "Nirjuli",
    "Chimpu",
    "Niti Vihar",
    "Ganga",
    "Naharlagun Township",
    "Midpu",
    "Jullang",
    "Lekhi",
    "Koha",
    "Hollongi",
    "Deoli",
    "Dikrong",
    "Paryaatan Nagar",
    "Papu Peak Area",
    "Gohpur (Ar)",
    "Balemu",
    "Chakma Area",
    "Miao Forest",
    "Panyor Valley",
    "Eagle Nest WLS",
    "Sela Pass Area",
    "Tawang Monastery Area",
    "Bumla Pass",
    "PT Tso Lake",
    "Madhuri Lake",
    "Shonga-tser Lake",
    "Tipi",
    "Ronggeur",
    "Thrizino",
    "Khobu",
    "Kwangsang",
    "Namgung",
    "Gorsam Chorten",
    "Zemithang",
    "Lungla",
    "Chhukha",
    "Lhou",
    "Kitpi",
    "Sangti Valley",
    "Dirang Dzong",
    "Bomdila Monastery",
    "Rupa Village",
    "Shergaon Village",
    "Kalaktang Town",
    "Nafra Town",
    "Janbari",
    "Bichom",
    "Panchen",
    "Thingbu",
    "Buragaon Village",
    "Bameng Village",
    "Pipu Village",
    "Chambang",
    "Naba",
    "Seppa Town",
    "Kimi",
    "Pipsorang",
    "Bana Camp",
    "Damin Village",
    "Sarli Village",
    "Taliha Village",
    "Nyapin Village",
    "Nacho Village",
    "Palin",
    "Potin",
    "Dollungmukh Town",
    "Tali Village",
    "Huri Village",
    "Tamen Village",
    "Yomcha",
    "Likha Valley",
    "Siyum",
    "Kaso",
    "Bopi",
    "Milin",
    "Rotung",
    "Ramong",
    "Geku",
    "Paindem",
    "Kebang",
    "Mebo Town",
    "Nari Area",
    "Tirbin Area",
    "Jonai Area",
    "Serkong",
    "Dirak",
    "Mechuka Valley",
    "Siyom Valley",
    "Tsangpo Gorge Area",
    "Pemako"
  ],

  "Assam": [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Karimganj",
    "Hailakandi",
    "Diphu",
    "North Lakhimpur",
    "Goalpara",
    "Barpeta",
    "Dhubri",
    "Sivasagar",
    "Golaghat",
    "Morigaon",
    "Kamrup",
    "Nalbari",
    "Bongaigaon",
    "Lakhimpur",
    "Cachar",
    "Chirang",
    "Darrang",
    "Dhemaji",
    "Dima Hasao",
    "Hojai",
    "Karbi Anglong",
    "Kokrajhar",
    "Majuli",
    "Sonitpur",
    "Udalguri",
    "Biswanath",
    "Bajali",
    "Tamulpur",
    "South Salmara",
    "Bajali (New District)",
    "Charaideo",
    "Baksa",
    "Mangaldoi",
    "Dispur",
    "Jalukbari",
    "Maligaon",
    "Christianbasti",
    "Paltanbazar",
    "Fancy Bazar",
    "Ambari",
    "Bhangagarh",
    "Ulubari",
    "Sixmile",
    "Narengi",
    "Beltola",
    "Zoo Road",
    "GS Road",
    "RG Baruah Road",
    "Ganeshguri",
    "Lakhtokia",
    "Chandmari",
    "Rehabari",
    "Hatigaon",
    "Kahilipara",
    "Zoo Narengi",
    "Noonmati",
    "Azara",
    "Bongaon",
    "Basistha",
    "Sonapur",
    "Khetri",
    "Mirza",
    "Chamata",
    "Hajo",
    "Sualkuchi",
    "Rangia",
    "Nalbari Town",
    "Tihu",
    "Sarthebari",
    "Barpeta Road",
    "Pathsala",
    "Baihata",
    "Barama",
    "Abhayapuri",
    "Kokrajhar Town",
    "Gossaigaon",
    "Bilasipara",
    "Gauripur",
    "Agomoni",
    "Dhubri Town",
    "Mankachar",
    "Golokganj",
    "South Salmara Town",
    "Duburi",
    "Salmara",
    "Fakirganj",
    "Bilasipara Town",
    "Dotma",
    "Soralmari",
    "Raniganj (Assam)",
    "Banskandi",
    "Lala",
    "Sarupathar",
    "Bokajan",
    "Bokakhat",
    "Dergaon",
    "Lanka",
    "Lumding",
    "Jagiroad",
    "Morigaon Town",
    "Kharupetia",
    "Dalgaon",
    "Mangaldoi Town",
    "Rowta",
    "Udalguri Town",
    "Bhergaon",
    "Tangla",
    "Kalaigaon",
    "Sipajhar",
    "Khoirabari",
    "Orang",
    "Bihali",
    "Biswanath Chariali",
    "Gohpur",
    "Behali",
    "Dhekiajuli",
    "Balipara",
    "Chariduar",
    "Thelamara",
    "Bihaguri",
    "Missamari",
    "Batadrawa",
    "Borhat",
    "Sarupathar (Golaghat)",
    "Numaligarh",
    "Moranhat",
    "Titabor",
    "Dergaon Town",
    "Mariani",
    "Jorhat Town",
    "Majuli Island",
    "Nimati Ghat",
    "Neamatighat",
    "Sibsagar (Sivasagar)",
    "Sonari",
    "Amguri",
    "Nazira",
    "Sarupathar (Sivasagar)",
    "Gaurisagar",
    "Gargaon",
    "Charaideo Moidam",
    "Sekoni",
    "Demow",
    "Sissiborgaon",
    "Moran",
    "Duliajan",
    "Digboi",
    "Margherita",
    "Makum",
    "Doom Dooma",
    "Bordumsa (Assam)",
    "Sadiya",
    "Dhola",
    "Saikhowa",
    "Tinsukia Town",
    "Ledo",
    "Lekhapani",
    "Panitola",
    "Namrup",
    "Doomdooma",
    "Naharkatia",
    "Moran Town",
    "Dibrugarh Town",
    "Rajgarh (Assam)",
    "Chabua",
    "Mohanbari",
    "North Lakhimpur Town",
    "Dhakuakhana",
    "Lakhimpur Town",
    "Bihpuria",
    "Naoboicha",
    "Ghiladhari",
    "Boginadi",
    "Nowboicha",
    "Jonai",
    "Sissi (Assam)",
    "Roing (Assam)",
    "Pasighat (Assam)",
    "Teok",
    "Senchoa",
    "Ambikapur (Assam)",
    "Dimaruguri",
    "Dhemaji Town",
    "Machkhowa",
    "Jonbeel",
    "Jonbeel Mela",
    "Sadia",
    "Kakopathar",
    "Deomornoi",
    "Doom Dooma Town",
    "Makum Junction",
    "Jagun",
    "Bordoloni",
    "Rampur (Assam)",
    "Kalain",
    "Sonai",
    "Jiribam (Assam)",
    "Lakhipur (Assam)",
    "Badarpurghat",
    "Udharbond",
    "Algapur",
    "Silcoorie",
    "Dharampur (Assam)",
    "Palonghat",
    "Harangajao",
    "Halflong",
    "Maibang",
    "Mahur",
    "Langting",
    "Umrangso",
    "Jatinga",
    "Haflong",
    "Bokajan Town",
    "Mawryngkneng",
    "Diphu Town",
    "Bokajan (KA)",
    "Hamren",
    "Howraghat",
    "Karbi Anglong HQ",
    "Donkamokam",
    "Rongmongwe",
    "Baithalangso",
    "Socheng",
    "Nongpoh (Assam)",
    "Baghbar",
    "Panbari",
    "Chirang Town",
    "Bijni",
    "Sidli",
    "Boitamari",
    "Bengtol",
    "Runikhata",
    "Ripu"
  ],
  "Bihar": [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Ara",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chhapra",
    "Bettiah",
    "Motihari",
    "Saharsa",
    "Sasaram",
    "Hajipur",
    "Jehanabad",
    "Nawada",
    "Buxar",
    "Siwan",
    "Sitamarhi",
    "Madhubani",
    "Supaul",
    "Gopalganj",
    "Kishanganj",
    "Araria",
    "Sheohar",
    "Lakhisarai",
    "Sheikhpura",
    "Nalanda",
    "Rohtas",
    "Kaimur",
    "Jamui",
    "Aurangabad",
    "Banka",
    "Khagaria",
    "Madhepura",
    "Vaishali",
    "East Champaran",
    "West Champaran",
    "Patna City",
    "Phulwari Sharif",
    "Danapur",
    "Khagaul",
    "Bihta",
    "Maner",
    "Fatwah",
    "Barh",
    "Mokama",
    "Bakhtiyarpur",
    "Rajgir",
    "Nalanda Town",
    "Biharsharif",
    "Islampur",
    "Hilsa",
    "Asthawan",
    "Ekangarsarai",
    "Silao",
    "Giryak",
    "Bind",
    "Bodh Gaya",
    "Sherghati",
    "Atri",
    "Tekari",
    "Gurua",
    "Barachatti",
    "Belaganj",
    "Mohanpur",
    "Imamganj",
    "Dobhi",
    "Hazaribagh (Bihar)",
    "Barhi (Bihar)",
    "Ramgarh (Bihar)",
    "Giridih (Bihar)",
    "Dhanbad (Bihar)",
    "Bokaro (Bihar)",
    "Deoghar (Bihar)",
    "Dumka (Bihar)",
    "Godda (Bihar)",
    "Sahibganj (Bihar)",
    "Muzaffarpur City",
    "Motipur",
    "Sitamarhi Town",
    "Sheohar Town",
    "Dumra",
    "Runni Saidpur",
    "Pupri",
    "Belsand",
    "Majorganj",
    "Dheng",
    "Darbhanga City",
    "Baheri",
    "Biraul",
    "Benipur",
    "Jale",
    "Ghanshyampur",
    "Singhwara",
    "Gaura Bauram",
    "Kusheshwar Asthan",
    "Hayaghat",
    "Madhubani Town",
    "Jhanjharpur",
    "Phulparas",
    "Jaynagar",
    "Madhepur",
    "Babubarhi",
    "Khajauli",
    "Benipatti",
    "Rahika",
    "Laukaha",
    "Supaul Town",
    "Chhatapur",
    "Triveniganj",
    "Salkhua",
    "Pipra",
    "Birpur",
    "Raghopur",
    "Nirmali",
    "Saraigarh",
    "Bhaptiyahi",
    "Saharsa Town",
    "Simri Bakhtiyarpur",
    "Mahishi",
    "Sour Bazar",
    "Banmankhi",
    "Purnia Town",
    "Baisi",
    "Rupauli",
    "Kasba",
    "Dhamdaha",
    "Katihar Town",
    "Manihari",
    "Barari",
    "Kadwa",
    "Sameli",
    "Mansahi",
    "Barsoi",
    "Pothia",
    "Pranpur",
    "Balrampur (Bihar)",
    "Kishanganj Town",
    "Thakurganj",
    "Kochadhaman",
    "Digohal",
    "Bahādurābād",
    "Araria Town",
    "Forbesganj",
    "Jokihat",
    "Raniganj (Bihar)",
    "Palasi",
    "Begusarai City",
    "Teghra",
    "Bachhwara",
    "Barauni",
    "Bhagalpur City",
    "Kahalgaon",
    "Pirpainti",
    "Sultanganj",
    "Sabour",
    "Naugachia",
    "Banka Town",
    "Amarpur",
    "Belhar",
    "Dhuraiya",
    "Khaira",
    "Munger City",
    "Tarapur",
    "Kharagpur (Bihar)",
    "Hajipur Town",
    "Lalganj",
    "Sonepur",
    "Manjhi",
    "Revelganj",
    "Siwan Town",
    "Maharajganj",
    "Hussainganj",
    "Gopalganj Town",
    "Kuchaikote",
    "Barauli",
    "Uchkagaon",
    "Bettiah Town",
    "Bagaha",
    "Narkatiaganj",
    "Raxaul",
    "Motihari Town",
    "Adapur",
    "Areraj",
    "Kesaria",
    "Pakridayal",
    "Chakia",
    "Buxar Town",
    "Dumraon",
    "Rajpur",
    "Brahampur",
    "Itarhi",
    "Chhapra Town",
    "Marhaura",
    "Mairwa",
    "Ekma",
    "Dighwara",
    "Ara City",
    "Piro",
    "Jagdishpur",
    "Koilwar",
    "Udwantnagar",
    "Sandesh",
    "Jehanabad Town",
    "Makhdumpur",
    "Hulasganj",
    "Ratnifaridpur",
    "Nawada Town",
    "Rajauli",
    "Warsaliganj",
    "Hisua",
    "Govindpur (Bihar)",
    "Sasaram Town",
    "Dehri",
    "Nasriganj",
    "Shivsagar",
    "Nokha",
    "Aurangabad Town",
    "Daudnagar",
    "Obra",
    "Rafiganj",
    "Dev",
    "Jamui Town",
    "Jhajha",
    "Chakai",
    "Sikandra (Bihar)",
    "Sono",
    "Lakhisarai Town",
    "Suryagarha",
    "Ramgarh Chowk",
    "Pipariya (Bihar)",
    "Sheikhpura Town",
    "Barbigha",
    "Asarganj",
    "Khagaria Town",
    "Mansi",
    "Alauli"
  ],
};
